### ISSUE TITLE
Problems with Path of numbers array

### ISSUE THREAD

**Issue by alexbars3d** [jonschlinkert/set-value#31] opened 2021-05-18 16:32 UTC
// argsPath = [ '505', '508' ]
 set(obj, argsPath, metrics);

returns:
{
      "505": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
(508 times null) ]
}

P.S. it wasworking on on version 3.0.2

**Comment by jonschlinkert** [comment] 2021-09-12 07:01
I get the following:

```js
const obj = {};
const argsPath = [ '505', '508' ];
set(obj, argsPath);

console.log(obj);
//=> { '505': [] }
```

Without knowing what `obj` and `metrics` are, it's difficult to know what's causing your bug, or if it's related to this library or something else.

**Comment by jonschlinkert** [comment] 2021-09-12 07:38
Closing for now since I can't reproduce this. Please feel free to reopen or create another issue with more details if you experience this bug.

**Closed by jonschlinkert** 2021-09-12 07:38 UTC
